export const defaultParentStatusPresets = [
  {
    label: "Cooking",
    activity: "Cooking dinner",
    availability: "helper-welcome",
    timeNeededMinutes: 20,
    space: "Kitchen table",
    messLevel: "low",
    noiseLevel: "normal",
    supervisionLevel: "nearby",
  },
  {
    label: "Cleaning",
    activity: "Cleaning the house",
    availability: "helper-welcome",
    timeNeededMinutes: 20,
    space: "Living room",
    messLevel: "low",
    noiseLevel: "normal",
    supervisionLevel: "nearby",
  },
  {
    label: "Work call",
    activity: "On a work call",
    availability: "do-not-interrupt",
    timeNeededMinutes: 30,
    space: "Living room",
    messLevel: "low",
    noiseLevel: "quiet",
    supervisionLevel: "independent",
  },
  {
    label: "Paying bills",
    activity: "Paying bills",
    availability: "ask-first",
    timeNeededMinutes: 20,
    space: "Kitchen table",
    messLevel: "low",
    noiseLevel: "quiet",
    supervisionLevel: "mostly-independent",
  },
  {
    label: "Resting",
    activity: "Resting",
    availability: "do-not-interrupt",
    timeNeededMinutes: 30,
    space: "Bedroom",
    messLevel: "low",
    noiseLevel: "quiet",
    supervisionLevel: "independent",
  },
  {
    label: "Yard work",
    activity: "Doing yard work",
    availability: "helper-welcome",
    timeNeededMinutes: 30,
    space: "Backyard",
    messLevel: "medium",
    noiseLevel: "normal",
    supervisionLevel: "nearby",
  },
  {
    label: "Errands",
    activity: "Handling errands",
    availability: "ask-first",
    timeNeededMinutes: 15,
    space: "Living room",
    messLevel: "low",
    noiseLevel: "normal",
    supervisionLevel: "mostly-independent",
  },
  {
    label: "Helping sibling",
    activity: "Helping someone else",
    availability: "ask-first",
    timeNeededMinutes: 20,
    space: "Living room",
    messLevel: "low",
    noiseLevel: "normal",
    supervisionLevel: "mostly-independent",
  },
];

export const inventoryCategories = [
  "Building toys",
  "Art supplies",
  "Outdoor gear",
  "Pretend play",
  "Books",
  "Board games",
  "Household-safe items",
  "STEM / experiments",
  "Quiet activities",
  "Other",
];
