// server/index.js

import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import helmet from "helmet";
import path from "path";
import { fileURLToPath } from "url";

import { createOpenAIClient } from "./lib/openaiClient.js";
import healthRouter from "./routes/health.js";
import createActivitySuggestionsRouter from "./routes/activitySuggestions.js";
import createQuestStepHintRouter from "./routes/questStepHint.js";

/*
 * ES modules do not automatically provide __filename and __dirname.
 *
 * We create them here so the server can reliably locate:
 *   1. server/.env during local development
 *   2. the React dist folder during production
 */
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/*
 * Load the local server environment file.
 *
 * Local file:
 *   family-activity-helper/server/.env
 *
 * In production, Railway or Render supplies environment variables through
 * its dashboard. The deployed application does not need this file to exist.
 */
dotenv.config({
  path: path.join(__dirname, ".env"),
});

const app = express();
const PORT = process.env.PORT || 3001;

/*
 * Railway and Render place a reverse proxy in front of Express.
 *
 * This setting tells Express that the first proxy is trusted. That allows
 * req.ip, secure cookies, and future rate-limiting middleware to determine
 * the original visitor information correctly.
 *
 * Keep this directly after:
 *
 *   const app = express();
 */
app.set("trust proxy", 1);

/*
 * Add standard HTTP security headers.
 *
 * Content Security Policy is temporarily disabled because the future app
 * will load resources from Supabase, Stripe, and Cloudflare Turnstile.
 *
 * We will configure a real CSP after those services are connected.
 */
app.use(
  helmet({
    contentSecurityPolicy: false,
  })
);

/*
 * During local development:
 *
 * React runs through Vite, usually at:
 *   http://localhost:5173
 *
 * Express runs at:
 *   http://localhost:3001
 *
 * Because those are different origins, development requires CORS.
 *
 * In production, React and Express will share one domain, so general CORS
 * access is unnecessary.
 */
if (process.env.NODE_ENV !== "production") {
  app.use(
    cors({
      origin: /^http:\/\/localhost:\d+$/,
    })
  );
}

/*
 * Confirm the server has the OpenAI key before creating the client.
 *
 * Local:
 *   family-activity-helper/server/.env
 *
 * Production:
 *   Add OPENAI_API_KEY in Railway or Render's environment-variable settings.
 */
if (!process.env.OPENAI_API_KEY) {
  console.error(
    "OPENAI_API_KEY is not set. Add it to server/.env locally or the hosting environment in production."
  );

  process.exit(1);
}

const client = createOpenAIClient();

/*
 * IMPORTANT FUTURE STRIPE LOCATION
 * --------------------------------
 *
 * When Stripe is added, its webhook route must go HERE:
 *
 *   app.post(
 *     "/api/billing/webhook",
 *     express.raw({ type: "application/json" }),
 *     stripeWebhookHandler
 *   );
 *
 * It must be placed before app.use(express.json()) because Stripe webhook
 * signature verification requires the original, unparsed request body.
 *
 * Do not add the Stripe route yet because stripeWebhookHandler does not
 * exist yet.
 */

/*
 * Parse normal application requests as JSON.
 *
 * This applies to activity generation, quest hints, and most future API
 * endpoints.
 */
app.use(express.json());

/*
 * API ROUTES
 * ----------
 *
 * Every backend route must be registered before the React frontend fallback.
 */
app.use("/api", healthRouter);
app.use("/api", createActivitySuggestionsRouter(client));
app.use("/api", createQuestStepHintRouter(client));

/*
 * API-ONLY 404
 * ------------
 *
 * Requests beginning with /api that do not match a real endpoint receive
 * JSON.
 *
 * This is intentionally scoped to "/api". It must not handle React routes.
 */
app.use("/api", (req, res) => {
  res.status(404).json({
    error: "API route not found.",
  });
});

/*
 * REACT PRODUCTION BUILD
 * ----------------------
 *
 * Running:
 *
 *   npm run build
 *
 * creates:
 *
 *   family-activity-helper/dist/
 *
 * Since this file is inside:
 *
 *   family-activity-helper/server/
 *
 * "../dist" moves up one directory and enters the Vite build folder.
 */
const clientDistPath = path.resolve(__dirname, "../dist");

/*
 * Serve JavaScript, CSS, images, fonts, and other files generated by Vite.
 */
app.use(express.static(clientDistPath));

/*
 * REACT ROUTER FALLBACK
 * ---------------------
 *
 * Any request that did not match an API endpoint or static file receives
 * React's index.html.
 *
 * This lets routes continue working when someone:
 *
 *   - refreshes a React page
 *   - bookmarks a React route
 *   - opens a React route directly
 *
 * This must remain after every /api route.
 */
app.get("*", (req, res) => {
  res.sendFile(path.join(clientDistPath, "index.html"));
});

/*
 * Start Express.
 *
 * Railway or Render supplies process.env.PORT.
 * Local development falls back to port 3001.
 */
app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});