// src/features/app/buildDomainContextValues.js

import ParentPinForm from "../../components/ParentPinForm";
import { inventoryCategories } from "../../constants/presets";
import { inventoryPresets } from "../../constants/inventoryPresets";
import { formatFeedbackLabel } from "../../utils/activityFormatters";

export function buildFamilyContextValue(input) {
  return {
    currentMoment: input.currentMoment,
    inventory: input.inventory,
    showStatus: input.showStatus,
    safetySettings: input.safetySettings,
    toggleSafetySetting: input.toggleSafetySetting,
    updateSafetySetting: input.updateSafetySetting,
    activityPreferences: input.activityPreferences,
    updateActivityPreference: input.updateActivityPreference,
    assumeHouseholdBasics: input.assumeHouseholdBasics,
    setAssumeHouseholdBasics: input.setAssumeHouseholdBasics,
    inventoryCategories,
    inventoryPresets,
    normalizedInventory: input.normalizedInventory,
    customInventoryItems: input.customInventoryItems,
    isInventoryItemSelected: input.isInventoryItemSelected,
    toggleInventoryPreset: input.toggleInventoryPreset,
    newInventoryItem: input.newInventoryItem,
    setNewInventoryItem: input.setNewInventoryItem,
    newInventoryCategory: input.newInventoryCategory,
    setNewInventoryCategory: input.setNewInventoryCategory,
    addInventoryItem: input.addInventoryItem,
    addInventoryItemFromScan: input.addInventoryItemFromScan,
    updateInventoryItem: input.updateInventoryItem,
    removeInventoryItem: input.removeInventoryItem,
    childProfiles: input.childProfiles,
    activeChildId: input.activeChildId,
    setActiveChildId: (childId) => input.applyPlayingSelection([childId]),
    activeChildProfile: input.activeChildProfile,
    selectedChildProfiles: input.selectedChildProfiles,
    playingChildIds: input.playingChildIds,
    togglePlayingChild: input.togglePlayingChild,
    activityMode: input.activityMode,
    setActivityMode: input.setActivityMode,
    newChildName: input.newChildName,
    setNewChildName: input.setNewChildName,
    newChildAgeRange: input.newChildAgeRange,
    setNewChildAgeRange: input.setNewChildAgeRange,
    newChildBirthDate: input.newChildBirthDate,
    setNewChildBirthDate: input.setNewChildBirthDate,
    newChildAgeYears: input.newChildAgeYears,
    setNewChildAgeYears: input.setNewChildAgeYears,
    agePreviewYears: input.agePreviewYears,
    newChildInterests: input.newChildInterests,
    setNewChildInterests: input.setNewChildInterests,
    newChildNeeds: input.newChildNeeds,
    setNewChildNeeds: input.setNewChildNeeds,
    newChildAvoids: input.newChildAvoids,
    setNewChildAvoids: input.setNewChildAvoids,
    newChildIndependenceLevel: input.newChildIndependenceLevel,
    setNewChildIndependenceLevel: input.setNewChildIndependenceLevel,
    editingChildId: input.editingChildId,
    showChildForm: input.showChildForm,
    beginAddingChildProfile: input.beginAddingChildProfile,
    startEditingChildProfile: input.startEditingChildProfile,
    cancelEditingChildProfile: input.cancelEditingChildProfile,
    addChildProfile: input.addChildProfile,
    deleteChildProfile: input.deleteChildProfile,
    parentPin: input.parentPin,
    ParentPinForm,
    saveParentPin: input.saveParentPin,
    savedActivities: input.savedActivities,
    handleReplaySavedActivity: input.handleReplaySavedActivity,
    removeSavedActivity: input.removeSavedActivity,
    activityHistory: input.activityHistory,
    clearActivityHistory: input.clearActivityHistory,
    resetLearnedRecommendations: input.resetLearnedRecommendations,
    formatFeedbackLabel,
    resetSavedData: input.resetSavedData,
    uiTheme: input.uiTheme,
    setUiTheme: input.setUiTheme,
    uiThemes: input.uiThemes,
    kidDeviceMode: input.kidDeviceMode,
    setKidDeviceMode: input.setKidDeviceMode,
    readingModePreference: input.readingModePreference,
    setReadingModePreference: input.setReadingModePreference,
    updateReadingModeSettings: input.updateReadingModeSettings,
    reapplyLastSuccessfulMoment: input.reapplyLastSuccessfulMoment,
    setupNudgeNeeded: input.setupNudgeNeeded,
    inventoryEmpty: input.inventoryEmpty,
    gettingBetterCopy: input.gettingBetterCopy,
  };
}

export function buildQuestContextValue(input) {
  return {
    currentMoment: input.currentMoment,
    activeActivity: input.activeActivity,
    lastCompletedQuest: input.lastCompletedQuest,
    clearLastCompletedQuest: input.clearLastCompletedQuest,
    handleCompletedQuestMoreLikeThis: input.handleCompletedQuestMoreLikeThis,
    handleCompletedQuestNeedAnotherIdea:
      input.handleCompletedQuestNeedAnotherIdea,
    finishActiveActivity: input.finishActiveActivity,
    cancelActiveActivity: input.cancelActiveActivity,
    handleSessionOutcome: input.handleSessionOutcome,
    handleTimerNotFinished: input.handleTimerNotFinished,
    handleTimerNeedAnotherIdea: input.handleTimerNeedAnotherIdea,
    handleTimerMoreLikeThis: input.handleTimerMoreLikeThis,
    goToNextQuestStep: input.goToNextQuestStep,
    goToPreviousQuestStep: input.goToPreviousQuestStep,
    toggleQuestStepComplete: input.toggleQuestStepComplete,
    toggleShowAllQuestSteps: input.toggleShowAllQuestSteps,
    setQuestPhase: input.setQuestPhase,
    toggleStarterIdea: input.toggleStarterIdea,
    selectStepStarter: input.selectStepStarter,
    assignRole: input.assignRole,
    toggleBuiltInHelp: input.toggleBuiltInHelp,
    setOpenSection: input.setOpenSection,
    openRescueSection: input.openRescueSection,
    markRescueModeUsed: input.markRescueModeUsed,
    stepHint: input.stepHint,
    isHintLoading: input.isHintLoading,
    hintLoadingStepIndex: input.hintLoadingStepIndex,
    handleNeedStepHint: input.handleNeedStepHint,
    completeListeningIntro: input.completeListeningIntro,
    setActivityReadingModeEnabled: input.setActivityReadingModeEnabled,
    completeSetup: input.completeSetup,
    toggleSetupCollapsed: input.toggleSetupCollapsed,
    activities: input.activities,
    scoredActivities: input.scoredActivities,
    activitySessions: input.activitySessions,
    isLoading: input.isLoading,
    generationFailed: input.generationFailed,
    generationErrorMessage: input.generationErrorMessage,
    retryLastGeneration: input.retryLastGeneration,
    handleStartActivity: input.handleStartActivityFromUi,
    saveFavoriteActivity: input.saveFavoriteActivity,
    handleTooMessy: input.handleTooMessy,
    handleTooHard: input.handleTooHard,
    handleTooYoung: input.handleTooYoung,
    handleTooOld: input.handleTooOld,
    handleTooEasy: input.handleTooEasy,
    handleNeedQuieter: input.handleNeedQuieter,
    handleMoreLikeThis: input.handleMoreLikeThis,
    handleTryNextBest: input.handleTryNextBestWithLibrary,
    handleAutoPickQuest: input.handleAutoPickQuest,
    gettingBetterCopy: input.gettingBetterCopy,
    selectedChildProfiles: input.selectedChildProfiles,
    setupNudgeNeeded: input.setupNudgeNeeded,
    inventoryEmpty: input.inventoryEmpty,
    entitlement: input.entitlement,
    entitlementHydrated: input.entitlementHydrated,
  };
}

export function buildBillingContextValue(input) {
  return {
    entitlement: input.entitlement,
    entitlementHydrated: input.entitlementHydrated,
    refreshEntitlement: input.refreshEntitlement,
  };
}

export function buildActivityContextValue(input) {
  return {
    activities: input.activities,
    setActivities: input.setActivities,
    scoredActivities: input.scoredActivities,
    isLoading: input.isLoading,
    loadingIntent: input.loadingIntent,
    generationFailed: input.generationFailed,
    generationErrorMessage: input.generationErrorMessage,
    handleGenerateActivities: input.handleGenerateActivities,
    retryLastGeneration: input.retryLastGeneration,
    handleGenerateKidActivities: input.handleGenerateKidActivities,
    handleStartSomethingForMe: input.handleStartSomethingForMe,
    handleStartActivityFromUi: input.handleStartActivityFromUi,
    handleAutoPickQuest: input.handleAutoPickQuest,
    saveFavoriteActivity: input.saveFavoriteActivity,
    removeSavedActivity: input.removeSavedActivity,
    freeImaginativeUnlockUsed: input.freeImaginativeUnlockUsed,
    imBoredDisabled: input.imBoredDisabled,
    isDemoMode: input.isDemoMode,
  };
}
